#! /bin/sh
### BEGIN INIT INFO
# Provides:          MeinProgramm
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts & Stops My Programm
# Description:       Starts & Stops My Programm
### END INIT INFO
 
#Switch case fuer den ersten Parameter
case "$1" in
    start)
 #Aktion wenn start uebergeben wird
        echo "Starte Vlc"
	# muss warten bis mit internetverbunden, daher sleep eingebaut
	sleep 10
	sudo -u pi cvlc -I http --http-port 43822 --http-password hello /home/pi/playlist.m3u > /dev/null
        ;;
 
    stop)
 #Aktion wenn stop uebergeben wird
        echo "Stoppe MeinProgramm"
        ;;
 
    restart)
 #Aktion wenn restart uebergeben wird
        echo "Restarte MeinProgramm"
        ;;
 *)
 #Standard Aktion wenn start|stop|restart nicht passen
 echo "(start|stop|restart)"
 ;;
esac
 
exit 0
